[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]
# Forzar overlay para evitar conflictos si nixpacks intenta meter node 18
nixOverlays = ["https://github.com/nixos/nixpkgs/archive/af9e00071d0971eb2ffd507d1002b5a54d2e6765.tar.gz"]

[phases.build]
cmds = ["npm ci", "npx prisma generate", "npm run build"]

[start]
cmd = "npm start"
